- name: ubuntu config
  hosts: ubuntu
  tasks:
    - name: create the .ssh directory if not present
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: 0700
    - name: create the authorized_keys file
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: touch
        mode: '0600'
    - name: copy over key block and append to authorized_keys
      blockinfile:
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        block: "{{ public_key }}"
    - name: create sudoers dropin file for 480
      file:
        path: /etc/sudoers.d/480
        state: touch
        mode: 0440
      become: yes
    - name: create a drop in entry in /etc/sudoers.d/480
      blockinfile:
        dest: /etc/sudoers.d/480
        block: "{{ ansible_user }}  ALL=(ALL)  NOPASSWD: ALL"
      become: yes
    - name: set the hostname
      hostname:
        name: "{{ hostname }}"
      become: yes

    - name: add host to hosts file
      lineinfile:
        path: /etc/hosts
        line: '127.0.1.1  {{ hostname}}'
      become: yes

    - name: configure netplan
      when: ansible_distribution == 'Ubuntu'
      template:
        src: ubuntu-netplan.j2
        dest: /etc/netplan/00-installer-config.yaml
      become: yes

    - name: reboot ubuntu servers and apply netplan
      when: ansible_distribution == 'Ubuntu'
      shell: netplan apply && sleep 5 && shutdown -r now
      become: yes
      async: 1
      poll: 0

