all:
  children:
    servers:
      hosts:
        dc-blue1:
          ansible_user: Administrator
          ansible_password: "{{ ansible_dc_password }}"
          ansible_connection: winrm
          ansible_host: 10.0.5.5
          ansible_winrm_transport: basic
          ansible_winrm_port: 5985
          ansible_winrm_server_cert_validation: ignore
